version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pg
    environment:
      POSTGRES_DB: jobkit
      POSTGRES_USER: jobkit
      POSTGRES_PASSWORD: jobkit
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  db-init:
    image: postgres:16-alpine
    depends_on:
      - postgres
    volumes:
      - ./init-db.sql:/01-init.sql        
    command: >
      sh -c "
        until pg_isready -h postgres -p 5432; do
          echo 'Waiting for postgres...';
          sleep 2;
        done;
        echo 'Creating tables...';
        psql -h postgres -U jobkit -d jobkit -f /01-init.sql
      "

  benchmark:
    build: ./benchmark
    container_name: pyjobkit-benchmark
    depends_on:
      - db-init
    environment:
      - DSN=postgresql+asyncpg://jobkit:jobkit@postgres:5432/jobkit
      - ENQUEUE_RATE=200
      - CONCURRENCY=16
    ports:
      - "7777:7777"
    restart: unless-stopped

volumes:
  pg_data: